-- MySQL Script generated by MySQL Workbench
-- Sun Jun  1 20:58:23 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema prados2db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema prados2db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `prados2db` DEFAULT CHARACTER SET utf8 ;
USE `prados2db` ;

-- -----------------------------------------------------
-- Table `prados2db`.`Residentes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Residentes` (
  `idCedulaResidente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  PRIMARY KEY (`idCedulaResidente`),
  UNIQUE INDEX `cedula_UNIQUE` (`idCedulaResidente` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`Propietario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Propietario` (
  `idCedulaPropietario` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`idCedulaPropietario`),
  UNIQUE INDEX `id_cedula_propietario_UNIQUE` (`idCedulaPropietario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`Funcionarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Funcionarios` (
  `idCedula` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `celular` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NULL,
  UNIQUE INDEX `id_cedula_UNIQUE` (`idCedula` ASC) VISIBLE,
  PRIMARY KEY (`idCedula`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`Parqueadero`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Parqueadero` (
  `idParqueadero` INT NOT NULL,
  `tipo_parqueadero` VARCHAR(45) NULL,
  `estado` TINYINT NULL,
  `observaciones` VARCHAR(45) NULL,
  `Propietario_idCedulaPropietario` INT NOT NULL,
  `Funcionarios_idCedula` INT NOT NULL,
  PRIMARY KEY (`idParqueadero`),
  UNIQUE INDEX `id_parqueadero_UNIQUE` (`idParqueadero` ASC) VISIBLE,
  INDEX `fk_Parqueadero_Propietario1_idx` (`Propietario_idCedulaPropietario` ASC) VISIBLE,
  INDEX `fk_Parqueadero_Funcionarios1_idx` (`Funcionarios_idCedula` ASC) VISIBLE,
  CONSTRAINT `fk_Parqueadero_Propietario1`
    FOREIGN KEY (`Propietario_idCedulaPropietario`)
    REFERENCES `prados2db`.`Propietario` (`idCedulaPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Parqueadero_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idCedula`)
    REFERENCES `prados2db`.`Funcionarios` (`idCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`Apartamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Apartamento` (
  `idApartamento` INT NOT NULL,
  `tamañoApartamento` VARCHAR(45) NULL,
  `porcentaje` DECIMAL(5) NULL,
  `Propietario_idCedulaPropietario` INT NOT NULL,
  `Residentes_idCedulaResidente` INT NOT NULL,
  PRIMARY KEY (`idApartamento`),
  UNIQUE INDEX `id_apartamento_UNIQUE` (`idApartamento` ASC) VISIBLE,
  INDEX `fk_Apartamento_Propietario1_idx` (`Propietario_idCedulaPropietario` ASC) VISIBLE,
  INDEX `fk_Apartamento_Residentes1_idx` (`Residentes_idCedulaResidente` ASC) VISIBLE,
  CONSTRAINT `fk_Apartamento_Propietario1`
    FOREIGN KEY (`Propietario_idCedulaPropietario`)
    REFERENCES `prados2db`.`Propietario` (`idCedulaPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Apartamento_Residentes1`
    FOREIGN KEY (`Residentes_idCedulaResidente`)
    REFERENCES `prados2db`.`Residentes` (`idCedulaResidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`SalonesSociales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`SalonesSociales` (
  `idSalonesSocilales` INT NOT NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `tamaño` INT NULL,
  `sillas` INT NULL,
  `mesas` INT NULL,
  `valor` INT NULL,
  `observaciones` VARCHAR(45) NULL,
  `Propietario_idCedulaPropietario` INT NOT NULL,
  `Residentes_idCedulaResidente` INT NOT NULL,
  `Funcionarios_idCedula` INT NOT NULL,
  PRIMARY KEY (`idSalonesSocilales`),
  UNIQUE INDEX `idSalonesSocilales_UNIQUE` (`idSalonesSocilales` ASC) VISIBLE,
  INDEX `fk_SalonesSociales_Propietario1_idx` (`Propietario_idCedulaPropietario` ASC) VISIBLE,
  INDEX `fk_SalonesSociales_Residentes1_idx` (`Residentes_idCedulaResidente` ASC) VISIBLE,
  INDEX `fk_SalonesSociales_Funcionarios1_idx` (`Funcionarios_idCedula` ASC) VISIBLE,
  CONSTRAINT `fk_SalonesSociales_Propietario1`
    FOREIGN KEY (`Propietario_idCedulaPropietario`)
    REFERENCES `prados2db`.`Propietario` (`idCedulaPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalonesSociales_Residentes1`
    FOREIGN KEY (`Residentes_idCedulaResidente`)
    REFERENCES `prados2db`.`Residentes` (`idCedulaResidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_SalonesSociales_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idCedula`)
    REFERENCES `prados2db`.`Funcionarios` (`idCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `prados2db`.`Trasteos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `prados2db`.`Trasteos` (
  `idTrasteos` INT NOT NULL,
  `cedula` VARCHAR(45) NULL,
  `nombres` VARCHAR(45) NULL,
  `apellidos` VARCHAR(45) NULL,
  `fechaTrasteo` DATE NULL,
  `Propietario_idCedulaPropietario` INT NOT NULL,
  `Residentes_idCedulaResidente` INT NOT NULL,
  `Funcionarios_idCedula` INT NOT NULL,
  PRIMARY KEY (`idTrasteos`),
  UNIQUE INDEX `id_trasteos_UNIQUE` (`idTrasteos` ASC) VISIBLE,
  INDEX `fk_Trasteos_Propietario_idx` (`Propietario_idCedulaPropietario` ASC) VISIBLE,
  INDEX `fk_Trasteos_Residentes1_idx` (`Residentes_idCedulaResidente` ASC) VISIBLE,
  INDEX `fk_Trasteos_Funcionarios1_idx` (`Funcionarios_idCedula` ASC) VISIBLE,
  CONSTRAINT `fk_Trasteos_Propietario`
    FOREIGN KEY (`Propietario_idCedulaPropietario`)
    REFERENCES `prados2db`.`Propietario` (`idCedulaPropietario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trasteos_Residentes1`
    FOREIGN KEY (`Residentes_idCedulaResidente`)
    REFERENCES `prados2db`.`Residentes` (`idCedulaResidente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Trasteos_Funcionarios1`
    FOREIGN KEY (`Funcionarios_idCedula`)
    REFERENCES `prados2db`.`Funcionarios` (`idCedula`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
